### ISSUE TITLE
SimpleXML class not found

### ISSUE THREAD

**Issue by xv1t** [QuantumObject/docker-cakephp#7]
for working `Cake\Utility\Xml` CakePHP helper need a `php7.2-xml` package

Please  add to install package to the `Dockerfile` and update docker image
```bash
apt-get install php7.2-xml
```
After manual install this package class `SimpleXML` support is enabled ok

**Comment by angelrr7702** [comment]
add php-xml that will install php7.2-xml

sincerely
Angel Rodriguez

**Comment by xv1t** [comment]
thanx
